/**
 * Test-data seed — 12 dummy bot players (Bot1..Bot12), each with 3 active defense snapshots, so the
 * arena has plenty of defenders to attack while testing battles. Mirrors the cold-start seed
 * (`db/seed.ts`): each config is passed through the shared engine `validateSquad()` before it is
 * written (the same gate a human squad passes) and its power rating derived from that call. Configs are
 * drawn from `seed-test-bot-armies.json` — 36 unique, engine-valid v3 armies (generated by
 * `scripts/gen-test-bot-armies.ts`) assigned **bijectively** so all 36 defenders are distinct squads.
 *
 * Idempotent + refresh-aware: a Bot{n} that already exists is reused, and each defense slot is
 * filled on first run, **upgraded in place** when its seed army has improved (via
 * `upsertActiveDefense`), and left untouched otherwise — re-running never duplicates.
 *
 * Run:  npx dotenv -e .env.local -- tsx db/seed-test-bots.ts        (prod)
 *       npx dotenv -e .env.dev.local -- tsx db/seed-test-bots.ts    (local dev)
 */

import { eq } from "drizzle-orm";

import { validateSquad } from "../sim/validate";
import type { SquadConfig } from "./types";
import { getDb } from "./index";
import { users } from "./schema";
import { upsertActiveDefense } from "./seed-helpers";
import seedArmies from "./seed-test-bot-armies.json";

interface SeedArmy {
  name: string;
  config: SquadConfig;
}

const BOT_COUNT = 12;
const SLOTS = [0, 1, 2] as const;

async function seedTestBots(): Promise<{ bots: number; defenses: number }> {
  const db = getDb();

  // Validate the source configs once, up front — fail fast if any army is bad (defense-in-depth: the
  // generator already gates on validate(), this re-checks and derives each power rating).
  const armies = (seedArmies as SeedArmy[]).map((a) => {
    const v = validateSquad(a.config);
    if (!v.ok) throw new Error(`seed army '${a.name}' is invalid: ${v.errors.map((e) => e.code).join(", ")}`);
    return { name: a.name, config: a.config, powerRating: v.powerRating };
  });
  const needed = BOT_COUNT * SLOTS.length;
  if (armies.length < needed) {
    throw new Error(`need ${needed} unique armies for ${BOT_COUNT} bots × ${SLOTS.length} slots, have ${armies.length}`);
  }

  let bots = 0;
  let defenses = 0;

  for (let n = 1; n <= BOT_COUNT; n++) {
    const handle = `Bot${n}`;
    const email = `bot${n}@warform.local`;

    const existing = await db.select({ id: users.id }).from(users).where(eq(users.email, email)).limit(1);
    let userId: string;
    if (existing.length > 0) {
      userId = existing[0].id;
    } else {
      userId = crypto.randomUUID();
      await db.insert(users).values({ id: userId, email, handle, isBot: true });
      bots += 1;
    }

    for (const slot of SLOTS) {
      // Bijective assignment: bot n (1-based) slot s ⇒ army[(n-1)*3 + s], indices 0..35 with no reuse,
      // so every one of the 36 defenders is a distinct squad. Fill on first run, upgrade in place when
      // an army changes (via upsertActiveDefense), idempotent otherwise.
      const src = armies[(n - 1) * SLOTS.length + slot];
      const r = await upsertActiveDefense(db, {
        userId,
        slot,
        name: `${handle} — ${src.name}`,
        config: src.config,
        powerRating: src.powerRating,
      });
      if (r !== "kept") defenses += 1;
    }
  }

  return { bots, defenses };
}

seedTestBots()
  .then(({ bots, defenses }) => {
    console.log(`test-bot seed complete: ${bots} new bot(s), ${defenses} new defense(s).`);
    return getDb().$client.end();
  })
  .catch((e) => {
    console.error("test-bot seed failed:", e);
    process.exit(1);
  });
